# Generated by Django 4.1.2 on 2022-10-27 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_ingredient_recipe_ingredient_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='recipe',
        ),
    ]
